version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
    example-workflow:
      jobs:
        - heroku/deploy-via-git:
            api-key: 456cfc14-d5cc-4b63-b116-a544b238cfc9
            app-name: edevelopment 