export { default as Layout } from './Layout'
export { default as Product } from './Product'
export { default as Header } from './Header'
export { default as Modal } from './Modal'
export { default as MainSlider } from './MainSlider'
export { default as Footer } from './Footer'